schemes:
  cubic:
    name: TCP Cubic
    color: black
    marker: '*'
  vegas:
    name: TCP Vegas
    color: silver
    marker: 'h'
  bbr:
    name: TCP BBR
    color: gold
    marker: '^'
  ledbat:
    name: LEDBAT
    color: green
    marker: '<'
  pcc:
    name: PCC-Allegro
    color: cyan
    marker: '>'
  verus:
    name: Verus
    color: skyblue
    marker: 'H'
  sprout:
    name: Sprout
    color: orange
    marker: 'p'
  quic:
    name: QUIC Cubic
    color: magenta
    marker: '8'
  scream:
    name: SCReAM
    color: pink
    marker: '1'
  webrtc:
    name: WebRTC media
    color: brown
    marker: 'v'
  copa:
    name: Copa
    color: red
    marker: 'o'
  taova:
    name: TaoVA-100x
    color: gray
    marker: 'd'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
  pcc_experimental:
    name: PCC-Expr
    color: olive
    marker: '<'
  fillp:
    name: FillP
    color: violet
    marker: '+'
  indigo:
    name: Indigo
    color: indigo
    marker: 'D'
  fillp_sheep:
    name: FillP-Sheep
    color: violet
    marker: 'D'
  eagle-xentropy:
    name: Eagle Cross-Entropy
    color: gold
    marker: 'x'
  eagle-dqn-test:
    name: Eagle DQN Test
    color: blue
    marker: '+'
  eagle-cross-entropy-001:
    name: Eagle Cross-Entropy 001
    color: gold
    marker: 'x'
  eagle-cross-entropy-002:
    name: Eagle Cross-Entropy 002
    color: black
    marker: 'x'
  eagle-dqn-001:
    name: Eagle DQN 001
    color: red
    marker: '+'
  eagle-dqn-002:
    name: Eagle DQN 002
    color: green
    marker: '+'
  eagle-dqn-003:
    name: Eagle DQN 003
    color: blue
    marker: '+'
  eagle-dqn-004:
    name: Eagle DQN 004
    color: red
    marker: '*'
  eagle-dqn-005:
    name: Eagle DQN 005
    color: green
    marker: '*'
  eagle-dqn-006:
    name: Eagle DQN 006
    color: blue
    marker: '*'